# Generated by Django 2.0.12 on 2019-03-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(default=0.0, verbose_name='终端数据')),
                ('status', models.BooleanField(default=False, verbose_name='终端状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '终端信息',
                'verbose_name_plural': '终端信息',
            },
        ),
        migrations.CreateModel(
            name='TerminalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.SmallIntegerField(verbose_name='终端id')),
                ('terminal_name', models.CharField(max_length=20, verbose_name='终端名称')),
            ],
            options={
                'verbose_name': '终端信息',
                'verbose_name_plural': '终端信息',
            },
        ),
        migrations.CreateModel(
            name='TerminalType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='设备种类id')),
                ('type_name', models.CharField(max_length=20, verbose_name='设备种类名称')),
            ],
            options={
                'verbose_name': '终端设备',
                'verbose_name_plural': '终端设备',
            },
        ),
        migrations.AddField(
            model_name='terminalinfo',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.TerminalType', verbose_name='设备种类id'),
        ),
        migrations.AddField(
            model_name='terminaldata',
            name='terminal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.TerminalInfo', verbose_name='终端id'),
        ),
    ]
