# Generated by Django 2.0.12 on 2019-05-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_warningvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningvalue',
            name='terminal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exhibition.TerminalInfo', verbose_name='终端名称'),
        ),
    ]
